name: Test Object Interpolation
on:
  pull_request:
    types: [opened, synchronize, closed]
  issue_comment:
    types: [created]
  workflow_run:
    workflows: [Universum check]
    types: [completed]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created]

jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_NAME: ${{ github.event.pull_request.title }}
      PR_BASE: ${{ github.event.pull_request.base.ref }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_MERGED: ${{ github.event.pull_request.merged_by.login }}
      REVIEW_STATE: ${{ github.event.review.state }}
      REVIEW_AUTHOR: ${{ github.event.review.user.login }}
      REVIEW_COMMENT: ${{ github.event.review.body }}
      COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
      COMMENT_URL: ${{ github.event.comment.html_url }}
      COMMENT_FILE: ${{ github.event.comment.path }}
      COMMENT_BODY: ${{ github.event.comment.body }}
      COMMENT_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Test Object Directly
        run: |
          echo "--- DIRECT OBJECT ---"
          echo ">>>${{ github.event.comment }}<<<"

          if [[ ! -z "${{ github.event.comment }}" ]]; then
          ESCAPED_TEXT=`echo -e "$COMMENT_BODY"| sed 's/\&/\&amp;/g' | sed 's/</\&lt;/g' | sed 's/>/\&gt;/g'`
          if [[ ! -z "${{ github.event.pull_request }}" ]]; then
            TEXT=`echo -e "<b>"$COMMENT_AUTHOR"</b> posted the following comment to file <i>"$COMMENT_FILE"</i> in <a href=\"$COMMENT_URL\">PR#"$PR_NUMBER"</a>:\n<i>"$ESCAPED_TEXT"</i>"`
          else
            TEXT=`echo -e "<b>"$COMMENT_AUTHOR"</b> posted the following comment to issue <a href=\"$COMMENT_URL\">#"$COMMENT_NUMBER"</a>:\n<i>"$ESCAPED_TEXT"</i>"`
          fi
          echo $TEXT
          echo $ESCAPED_TEXT
          
      - name: Test Object with toJSON
        run: |
          echo "--- TOJSON OBJECT ---"
          echo ">>>${{ toJSON(github.event.comment) }}<<<"
          
      - name: Test String Property
        run: |
          echo "--- COMMENT BODY ---"
          echo ">>>${{ github.event.comment.body }}<<<"

  
